# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rgb_cnames.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 447)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color:azure;\n"
"color:black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color:#424242;\n"
"color:black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.rs = QtWidgets.QSlider(self.centralwidget)
        self.rs.setGeometry(QtCore.QRect(90, 110, 240, 50))
        self.rs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rs.setStyleSheet("QSlider {\n"
"/* スライダー全体*/\n"
"border-radius:10px;\n"
"border-color:#a1a1a1;\n"
"border-style:solid; \n"
"border-width:3px;\n"
"background-color:red;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    background: darkgray;\n"
"    height: 2px; /* 溝の高さ */\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -24px 0; /* 溝との位置を調整 */\n"
"    border-radius: 3px; /* 丸み */\n"
"}")
        self.rs.setMaximum(255)
        self.rs.setProperty("value", 126)
        self.rs.setOrientation(QtCore.Qt.Horizontal)
        self.rs.setInvertedAppearance(False)
        self.rs.setInvertedControls(False)
        self.rs.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.rs.setTickInterval(0)
        self.rs.setObjectName("rs")
        self.gs = QtWidgets.QSlider(self.centralwidget)
        self.gs.setGeometry(QtCore.QRect(90, 170, 240, 50))
        self.gs.setStyleSheet("QSlider {\n"
"/* スライダー全体*/\n"
"border-radius:10px;\n"
"border-color:#a1a1a1;\n"
"border-style:solid; \n"
"border-width:3px;\n"
"background-color:green;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    background: darkgray;\n"
"    height: 2px; /* 溝の高さ */\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -24px 0; /* 溝との位置を調整 */\n"
"    border-radius: 3px; /* 丸み */\n"
"}")
        self.gs.setMaximum(255)
        self.gs.setProperty("value", 126)
        self.gs.setOrientation(QtCore.Qt.Horizontal)
        self.gs.setInvertedAppearance(False)
        self.gs.setInvertedControls(False)
        self.gs.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.gs.setTickInterval(0)
        self.gs.setObjectName("gs")
        self.bs = QtWidgets.QSlider(self.centralwidget)
        self.bs.setGeometry(QtCore.QRect(90, 230, 240, 50))
        self.bs.setStyleSheet("QSlider {\n"
"/* スライダー全体*/\n"
"border-radius:10px;\n"
"border-color:#a1a1a1;\n"
"border-style:solid; \n"
"border-width:3px;\n"
"background-color:blue;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    background: darkgray;\n"
"    height: 2px; /* 溝の高さ */\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -24px 0; /* 溝との位置を調整 */\n"
"    border-radius: 3px; /* 丸み */\n"
"}")
        self.bs.setMaximum(255)
        self.bs.setProperty("value", 126)
        self.bs.setOrientation(QtCore.Qt.Horizontal)
        self.bs.setInvertedAppearance(False)
        self.bs.setInvertedControls(False)
        self.bs.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.bs.setTickInterval(0)
        self.bs.setObjectName("bs")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 10, 751, 45))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel{\n"
"border-radius:10px;\n"
"border-color:#a1a1a1;\n"
"border-style:solid; \n"
"border-width:4px;\n"
"background-color:snow;\n"
"color:black;\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.rgb = QtWidgets.QLabel(self.centralwidget)
        self.rgb.setGeometry(QtCore.QRect(30, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rgb.setFont(font)
        self.rgb.setStyleSheet("border-radius:8px;\n"
"border-color:#a1a1a1;\n"
"border-style:solid; \n"
"border-width:3px;\n"
"\n"
"background-color:white;\n"
"color:black;")
        self.rgb.setAlignment(QtCore.Qt.AlignCenter)
        self.rgb.setObjectName("rgb")
        self.hexL = QtWidgets.QLabel(self.centralwidget)
        self.hexL.setGeometry(QtCore.QRect(30, 300, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hexL.setFont(font)
        self.hexL.setStyleSheet("\n"
"border-color: black;\n"
"border-style:solid; \n"
"border-width:8px;\n"
"\n"
"background-color:white;\n"
"color:black;")
        self.hexL.setText("")
        self.hexL.setAlignment(QtCore.Qt.AlignCenter)
        self.hexL.setObjectName("hexL")
        self.rn = QtWidgets.QLabel(self.centralwidget)
        self.rn.setGeometry(QtCore.QRect(30, 110, 51, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rn.setFont(font)
        self.rn.setStyleSheet("border-radius:10px;\n"
"border-color:red;\n"
"border-style:solid; \n"
"border-width:4px;\n"
"\n"
"background-color:red;\n"
"color:white;")
        self.rn.setText("")
        self.rn.setAlignment(QtCore.Qt.AlignCenter)
        self.rn.setObjectName("rn")
        self.gn = QtWidgets.QLabel(self.centralwidget)
        self.gn.setGeometry(QtCore.QRect(30, 170, 51, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gn.setFont(font)
        self.gn.setStyleSheet("border-radius:10px;\n"
"border-color:green;\n"
"border-style:solid; \n"
"border-width:4px;\n"
"\n"
"background-color:green;\n"
"color:white;")
        self.gn.setText("")
        self.gn.setAlignment(QtCore.Qt.AlignCenter)
        self.gn.setObjectName("gn")
        self.bn = QtWidgets.QLabel(self.centralwidget)
        self.bn.setGeometry(QtCore.QRect(30, 230, 51, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bn.setFont(font)
        self.bn.setStyleSheet("border-radius:10px;\n"
"border-color:blue;\n"
"border-style:solid; \n"
"border-width:4px;\n"
"\n"
"background-color:blue;\n"
"color:white;")
        self.bn.setText("")
        self.bn.setAlignment(QtCore.Qt.AlignCenter)
        self.bn.setObjectName("bn")
        self.combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box.setGeometry(QtCore.QRect(370, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.combo_box.setFont(font)
        self.combo_box.setStyleSheet("QComboBox {\n"
"border-radius:8px;\n"
"border-color:#a1a1a1;\n"
"border-style:solid; \n"
"border-width:3px;\n"
"background-color:snow;\n"
"color:black;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"background-color: lightblue;   /* リスト部分の背景色 */\n"
"color: black;                  /* リスト部分のテキスト色 */\n"
"selection-background-color: darkblue; /* 選択項目の背景色 */\n"
"selection-color: white;        /* 選択項目のテキスト色 */\n"
"}\n"
"")
        self.combo_box.setObjectName("combo_box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(370, 110, 411, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 80, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color:white;\n"
"}")
        self.label.setObjectName("label")
        self.copyButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton1.setGeometry(QtCore.QRect(240, 380, 90, 32))
        self.copyButton1.setStyleSheet("QPushButton{\n"
"background-color:snow;\n"
"color:black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:gray;\n"
"color:white;\n"
"}")
        self.copyButton1.setObjectName("copyButton1")
        self.copyButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton2.setGeometry(QtCore.QRect(240, 70, 90, 32))
        self.copyButton2.setStyleSheet("QPushButton{\n"
"background-color:snow;\n"
"color:black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:gray;\n"
"color:white;\n"
"}")
        self.copyButton2.setObjectName("copyButton2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 284, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.cnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.cnameLabel.setGeometry(QtCore.QRect(90, 380, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cnameLabel.setFont(font)
        self.cnameLabel.setStyleSheet("QLabel{\n"
"background-color:snow;\n"
"color:black;\n"
"}")
        self.cnameLabel.setText("")
        self.cnameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cnameLabel.setObjectName("cnameLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 380, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "カラー作成ツール (RGB/HEX/cname)"))
        self.rgb.setText(_translate("MainWindow", "RGB(,,)"))
        self.label.setText(_translate("MainWindow", "カラーパレット(見本)の選択"))
        self.copyButton1.setText(_translate("MainWindow", "cnameコピー"))
        self.copyButton2.setText(_translate("MainWindow", "RGBコピー"))
        self.label_2.setText(_translate("MainWindow", "スライド操作で hex codeをコピー(default)"))
        self.label_3.setText(_translate("MainWindow", "cname"))
